### ISSUE TITLE
$('.body') classes

### ISSUE THREAD

**Issue by westyby** [lukesnowden/FSVS#18] opened 2015-06-21 08:25 UTC
Open the link http://luke.sno.wden.co.uk/full-screen-vertical-scroll#slide-3, don't scrolling and look at body classes:
<body class="active-slide-3 active-nth-slide-3 active-slide-1 active-nth-slide-1">
On window load, if we look at third slide, plugin says, that active is slideOne and slideThree
http://joxi.ru/bmobvbpHO7lZry

**Comment by lukesnowden** [comment] 2015-06-22 07:47
duplicate of your previous #19. also note that my site doesn't contain the most up to date codebase, GitHub does mate.

**Closed by lukesnowden** 2015-06-22 07:47 UTC

**Comment by lukesnowden** [comment] 2015-06-26 20:48
Use the repo mate that's the first version nearly a year ago... Should really update it...
